### ISSUE TITLE
Support for Lumen 10

### ISSUE THREAD

**Issue by miguelromeroccxc** [ssi-anik/form-request#11]
Do you know about this compatibility with lumen 10 for the plugin illuminate/support of Laravel 10

**Comment by mazfreelance** [comment]
> Do you know about this compatibility with lumen 10 for the plugin illuminate/support of Laravel 10

https://github.com/ssi-anik/form-request/pull/12

**Comment by ssi-anik** [comment]
sorry for the delayed response, I have tagged with `v5.*`. check on packagist.
