### ISSUE TITLE
Compatibility error

### ISSUE THREAD

**Issue by scristian9** [ssi-anik/form-request#7]
I am installing to the library in my project  and it throws me this in my Request that extends from its formRequest

**Method 'App\Http\Requests\Api\V1\AuthenticationRequest::rules()' is not compatible with method 'Anik\Form\FormRequest::rules()**

I already did the first steps that appear in the docs

My code is:

```php
namespace App\Http\Requests\Api\V1;

use Anik\Form\FormRequest;

class AuthenticationRequest extends FormRequest
{
    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'email' => 'required|email',
            'password' => 'required',
        ];
    }
}
```

what am I doing wrong?

I tried set rules function as protected and nothing the same error.

**Comment by ssi-anik** [comment]
You forgot to use the type hint in your request class, it should be like

```php
// ...
public function rules(): array {
    return [];
}
```
