### ISSUE TITLE
Lumen (9.0.1) (Laravel Components ^9.0)

### ISSUE THREAD

**Issue by yvescleuder** [ssi-anik/form-request#8]
Using version ^4.3 for anik/form-request
./composer.json has been updated
Running composer update anik/form-request
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires anik/form-request ^4.3 -> satisfiable by anik/form-request[v4.3].
    - anik/form-request v4.3 requires illuminate/support ^6.0|^7.0|^8.0 -> found illuminate/support[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but the package is fixed to v9.2.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require anik/form-request:*" to figure out if any version is installable, or "composer require anik/form-request:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by ssi-anik** [comment]
Thanks for informing. I will try to work and make a release.

**Comment by ssi-anik** [comment]
@yvescleuder It's going to take a few more days as the underlying packages need to be updated as well. I would request you to fork the project, change the composer.json with required changes and use it for urgency. After it's done in this package, you'll be notified here.

**Comment by ssi-anik** [comment]
@yvescleuder I have just tagged the branch with `v4.4`. You're good to go.
